# -*- coding: utf-8 -*-
"""Adaptor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NlK2tYRL0E1bqp8Q6NndzBPAUBNLIpiw
"""

# Target interface
class Target:
    def request(self):
        pass

# Adaptee (the class that needs to be adapted)
class Adaptee:
    def specific_request(self):
        print("Adaptee's specific request")

# Adapter class
class Adapter(Target):
    def __init__(self, adaptee):
        self.adaptee = adaptee

    def request(self):
        # Call the specific request method of the Adaptee
        self.adaptee.specific_request()

# Client code
def client_code(target):
    target.request()

# Create an instance of Adaptee
adaptee = Adaptee()

# Create an instance of Adapter, passing the Adaptee as an argument
adapter = Adapter(adaptee)

# Call the client code with the Adapter
client_code(adapter)